#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

RED=$(tput setaf 1)
NORMAL=$(tput sgr0)

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  # shellcheck disable=SC2059
  printf "\n${RED}Don't commit directly to the main branch.${NORMAL}\n\n"
  exit 1
fi

npx lint-staged
npm run package && git add dist
npm run test
